[package]
name = "actix-test"
version = "0.1.0"
authors = ["thehouseplant <sean.collins@outlook.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"

actix = "0.7"
actix-web = "0.7"